### ISSUE TITLE
Template json file

### ISSUE THREAD

**Issue by pcklink** [Herseninstituut/FYD_Matlab#1]
Can we get a template json file in this repo that indicates how the obligatory json fields should be called? Some people (me) want to be able to use the json-generation without a network connection where `getdbfields` won't work. The way I'm setting it up now is that it can be run (to initialize new entries server-side) but that we can also generate the necessary and supplemental json fields without querying the database. For that to result in error-free json files I need to now the required json-file structure. 

If this is already available somewhere and I missed it, please point me in the correct direction.

**Comment by chrisvdt** [comment]
added  a JSON file text template of required fields in the READ.ME
