### ISSUE TITLE
FYD link

### ISSUE THREAD

**Issue by pcklink** [Herseninstituut/FYD_Matlab#2]
The link in the readme to [http://nhi-fyd.nin.knaw.nl/ ](http://nhi-fyd.nin.knaw.nl/) gives a 'Red Hat Enterprise Linux Test Page'. With `https` instead of `http` it does work [https://nhi-fyd.nin.knaw.nl/](https://nhi-fyd.nin.knaw.nl/).

**Comment by chrisvdt** [comment]
should have been a https link. But I don't understand why it is giving this error now because it should be redirected to https

**Comment by chrisvdt** [comment]
Has been solved.

From: Chris Klink ***@***.***>
Sent: Thursday, July 1, 2021 4:58 PM
To: Herseninstituut/FYD_Matlab ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Herseninstituut/FYD_Matlab] FYD link (#2)


The link in the readme to http://nhi-fyd.nin.knaw.nl/ <https://eur05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fnhi-fyd.nin.knaw.nl%2F&data=04%7C01%7Cc.vandertogt%40nin.knaw.nl%7C424a8fa38d6740cc208208d93ca0a275%7Cac4b0eb0811e4ab0acca8a87079290dc%7C0%7C0%7C637607482881684250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Fxzb0ft5RmUDc7SiB%2FiRwRDFHXhq4F%2FJx6zeG%2FpXyJk%3D&reserved=0> gives a 'Red Hat Enterprise Linux Test Page'. Wrong link or something down?

-
